### ISSUE TITLE
when install in to got any issue but when logout "You don't have permission to view this list of course" 

### ISSUE THREAD

**Issue by pikou1985** [lmsace/enlightlite#26]
when install in to got any issue but when logout "You don't have permission to view this list of course"
I use moodle 3.11 whit sql server 2017.
I check in course_rederer.php 
        $sql = "SELECT a.category , a.cnt from ( SELECT category , count(category) as cnt FROM {course}";
        $sql .= " WHERE category != '0' and visible = ? group by category ) as a order by a.cnt desc ";

If i change visible !=1 or <>1 it show login page and can login but course menu not list down course.

I change $sql to default when logout it got error "You don't have permission to view this list of course".

**Comment by pikou1985** [comment]
when install in to got any issue but when logout "You don't have permission to view this list of course"

**Comment by prasanna-lmsace** [comment]
We have fixed the issue and updated the fix to branch m4.0. We will update the fix in other versions as soon as possible
