### ISSUE TITLE
Moodle 4.0

### ISSUE THREAD

**Issue by kedst** [lmsace/enlightlite#27]
After moodle is upgraded to 4.0, the Enlightlite theme displays everything black. Looks like black writing on a black background.  There is a white X displayed in the middle of the screen, but it doesn't do anthing. The moodle instance is innoperable with Enlightlite as the theme after the upgrade to v4.0

**Comment by pikou85** [comment]
as current l

> After moodle is upgraded to 4.0, the Enlightlite theme displays everything black. Looks like black writing on a black background. There is a white X displayed in the middle of the screen, but it doesn't do anthing. The moodle instance is innoperable with Enlightlite as the theme after the upgrade to v4.0

currently enlightlite not support with moodle 4.0.

**Comment by sukmawatinln** [comment]
any idea for solving this issue? I have the same problem too, minimum back to the default style or theme

**Comment by pikou85** [comment]
it support only moolde 3.11+

**Comment by prasanna-lmsace** [comment]
Enlightlite theme new version released to support Moodle 4.0.
