### ISSUE TITLE
enroll user issue

### ISSUE THREAD

**Issue by pikou85** [lmsace/enlightlite#28]
Enroll user and cohort --> select enroll it show blank. can anyone help
![moo](https://user-images.githubusercontent.com/52403531/168265871-d12d1f52-c9fa-4fec-b5c4-094241ca2adc.jpg)

**Comment by Nithyanandan-lms** [comment]
Hi pikou85,

There is no issue with the theme and please upgrade to the latest source. Also please check you have switched the enlightlite theme source branch to version-4.0 after cloning the theme.

![enlightlite-course-enrol](https://user-images.githubusercontent.com/44221518/168962653-2914fd8a-7df1-49af-945c-8d4d8675befe.png)

![switch-theme-branch](https://user-images.githubusercontent.com/44221518/168963630-6e1a068f-b4cf-4eb3-8b68-a69417bfbbfa.png)
