### ISSUE TITLE
Home page bug open and close block drawer

### ISSUE THREAD

**Issue by ecottis** [lmsace/enlightlite#29]
Im having issues with the open and close block drawer on the hompage.  

When clickng on the open or close icon nothing happens. 

Moddle version 4.01

**Comment by prasanna-lmsace** [comment]
Hi [ecottis](https://github.com/ecottis),

Thanks for reporting an issue. We have tested the enlightlite in the latest Moodle version, Block drawer works fine on our end.
Can you please share the URL to test?

Thanks,
Prasanna T

**Comment by ecottis** [comment]
Hi 

The url is https://sandbox.pet-xi-live.co.uk/

Login Guest1

Password Password1=

Note: this is a non live environment 

I've removed my CSS adaption to make it cleaner but issue is still there. 

I have noticed that this error does not show in Firefox however the drawer toggle link does not work correctly on either Ms Edge or Google Chrome browsers. That is why it might have been missed. 

Note Also I have posted another issue regarding the next button on the user privacy page as this is also missing.  However to let you to get in Accepted the policy for you if you would like me to reset so you can see this fault let me know.

**Comment by ecottis** [comment]
Thanks just took the update and all sorted. 
Great Theme
