### ISSUE TITLE
Button appears missing  on the user policy acceptance page

### ISSUE THREAD

**Issue by ecottis** [lmsace/enlightlite#30]
Hi 
I have found an error when using user policy's .  **When the learner enters the site for the 1st time the policy comes up but the 'Next button at the bottom is hidden.**  

Could you please put this on your issues list.  I’m sure others use this to ensure learners have committed to their user policies.  I have used another Theme to show the button in question. below

![image](https://user-images.githubusercontent.com/67025862/170370150-c0ee9abb-08e7-45c3-8a42-e83608eab94c.png)

Great theme in the making

**Comment by prasanna-lmsace** [comment]
Hi,

We have fixed the issue and released the new version v4.0.3. Please update your source and confirm whether the issue is fixed or not.

Thanks,
Prasanna T

**Comment by ecottis** [comment]
Hi Prasanna

It now shows a link but not a button. Can I suggest you use the same class as the next button on the next screen 'consent,
![image](https://user-images.githubusercontent.com/67025862/170929974-339ff454-c3ab-472a-be3e-e5445bc76113.jpeg)

![image](https://user-images.githubusercontent.com/67025862/170930016-7534f68f-c9f2-4203-b1e6-ef78c6cca680.jpeg)
